### ISSUE TITLE
classpath issues if plugin is in buildSrc/...

### ISSUE THREAD

**Issue by mlueders** [ldaley/gradle-test-kit#2]
This is more of a heads-up than anything else.  When I was initially experimenting with the test kit, I had a project with plugins in buildSrc.  The test kit did not function in that scenario but works perfectly if another build is not spawned.  I'm not sure how it would function in regular sub-projects (buildSrc seems to behave differently than standard sub-projects).  It's not really a problem for me since I've since moved the functionality into src for that project but figured I'd let ya know.

I can revert to an earlier version of my code and reproduce the problem if you'd like a more detailed description.

**Comment by ldaley** [comment]
Hi @mlueders,

Sorry, I missed this when it was posted. I'd very much like to get to the bottom of this, so if you could let me know how I can reproduce I'd appreciate it.

**Comment by mlueders** [comment]
Unfortunately, I can't seem to reproduce the problem.  The original repo is gone (closed source became open source with the condition that internal urls be removed, easiest way was to nuke history) and I must've been doing something funky b/c the straight forward case with buildSrc seems to work fine.  I've got a couple more things to try when I get some time but don't have high hopes that I'll be able to reproduce.  If so, I'll open another ticket along with a url to a repo which demonstrates the problem.

**Comment by ldaley** [comment]
Great, thanks @mlueders
